-- Current sql file was generated after introspecting the database
-- If you want to run this migration please uncomment this code before executing migrations
/*
CREATE TABLE "pg-drizzle_video" (
	"id" uuid PRIMARY KEY NOT NULL,
	"sourceVideoId" uuid,
	"name" varchar(255) NOT NULL,
	"cloudinaryPublicId" varchar(512),
	"s3FramesPrefix" varchar(512),
	"start_time_seconds" real,
	"totalFrames" integer NOT NULL,
	"fps" integer DEFAULT 30 NOT NULL,
	"width" integer NOT NULL,
	"height" integer NOT NULL,
	"status" varchar(50) DEFAULT 'ready' NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	"end_time_seconds" real,
	"processedFrames" integer DEFAULT 0 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name ""pg-drizzle_post_id_seq"" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1),
	"name" varchar(256),
	"createdById" varchar(255) NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_queue_config" (
	"id" uuid PRIMARY KEY NOT NULL,
	"reannotationPercentage" integer DEFAULT 30 NOT NULL,
	"updatedAt" timestamp with time zone,
	"updatedBy" text
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_user_video_progress" (
	"id" uuid PRIMARY KEY NOT NULL,
	"userId" text NOT NULL,
	"videoId" uuid NOT NULL,
	"lastAnnotatedFrame" integer DEFAULT 0 NOT NULL,
	"totalAnnotated" integer DEFAULT 0 NOT NULL,
	"status" varchar(50) DEFAULT 'in_progress' NOT NULL,
	"startedAt" timestamp with time zone NOT NULL,
	"lastActivity" timestamp with time zone NOT NULL,
	"completedAt" timestamp with time zone,
	CONSTRAINT "user_video_progress_unique" UNIQUE("videoId","userId")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_annotation" (
	"id" uuid PRIMARY KEY NOT NULL,
	"videoId" uuid NOT NULL,
	"userId" text NOT NULL,
	"frameNumber" integer NOT NULL,
	"x" real,
	"y" real,
	"ballVisible" boolean DEFAULT true NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "annotation_video_user_frame_unique" UNIQUE("videoId","userId","frameNumber")
);
--> statement-breakpoint
CREATE TABLE "pg-drizzle_source_video" (
	"id" uuid PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"s3Key" varchar(512) NOT NULL,
	"fps" real,
	"width" integer,
	"height" integer,
	"duration_seconds" real,
	"createdAt" timestamp with time zone NOT NULL
);
--> statement-breakpoint
ALTER TABLE "pg-drizzle_video" ADD CONSTRAINT "pg-drizzle_video_sourceVideoId_pg-drizzle_source_video_id_fk" FOREIGN KEY ("sourceVideoId") REFERENCES "public"."pg-drizzle_source_video"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_post" ADD CONSTRAINT "pg-drizzle_post_createdById_user_id_fk" FOREIGN KEY ("createdById") REFERENCES "public"."user"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_queue_config" ADD CONSTRAINT "pg-drizzle_queue_config_updatedBy_user_id_fk" FOREIGN KEY ("updatedBy") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_video_progress" ADD CONSTRAINT "pg-drizzle_user_video_progress_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_user_video_progress" ADD CONSTRAINT "pg-drizzle_user_video_progress_videoId_pg-drizzle_video_id_fk" FOREIGN KEY ("videoId") REFERENCES "public"."pg-drizzle_video"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_annotation" ADD CONSTRAINT "pg-drizzle_annotation_videoId_pg-drizzle_video_id_fk" FOREIGN KEY ("videoId") REFERENCES "public"."pg-drizzle_video"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pg-drizzle_annotation" ADD CONSTRAINT "pg-drizzle_annotation_userId_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "video_created_at_idx" ON "pg-drizzle_video" USING btree ("createdAt" timestamptz_ops);--> statement-breakpoint
CREATE INDEX "video_name_idx" ON "pg-drizzle_video" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "video_source_idx" ON "pg-drizzle_video" USING btree ("sourceVideoId" uuid_ops);--> statement-breakpoint
CREATE INDEX "created_by_idx" ON "pg-drizzle_post" USING btree ("createdById" text_ops);--> statement-breakpoint
CREATE INDEX "name_idx" ON "pg-drizzle_post" USING btree ("name" text_ops);--> statement-breakpoint
CREATE INDEX "idx_user_role" ON "pg-drizzle_user_video_progress" USING btree ("userId" text_ops);--> statement-breakpoint
CREATE INDEX "user_video_progress_status_idx" ON "pg-drizzle_user_video_progress" USING btree ("status" text_ops);--> statement-breakpoint
CREATE INDEX "user_video_progress_user_idx" ON "pg-drizzle_user_video_progress" USING btree ("userId" text_ops);--> statement-breakpoint
CREATE INDEX "user_video_progress_video_idx" ON "pg-drizzle_user_video_progress" USING btree ("videoId" uuid_ops);--> statement-breakpoint
CREATE INDEX "annotation_user_idx" ON "pg-drizzle_annotation" USING btree ("userId" text_ops);--> statement-breakpoint
CREATE INDEX "annotation_user_video_idx" ON "pg-drizzle_annotation" USING btree ("userId" text_ops,"videoId" uuid_ops);--> statement-breakpoint
CREATE INDEX "annotation_video_frame_idx" ON "pg-drizzle_annotation" USING btree ("videoId" int4_ops,"frameNumber" uuid_ops);--> statement-breakpoint
CREATE INDEX "annotation_video_idx" ON "pg-drizzle_annotation" USING btree ("videoId" uuid_ops);--> statement-breakpoint
CREATE INDEX "source_video_created_at_idx" ON "pg-drizzle_source_video" USING btree ("createdAt" timestamptz_ops);
*/